
services:
  nginx:
    build: .
    container_name: low-code-nginx
    ports:
      - "9100:9100"
    volumes:
      - ./lowCode:/usr/share/nginx/html
      - ./nginx.conf:/etc/nginx/nginx.conf
    restart: always

    networks:
      - low-code
networks:
  low-code:
    name: low-code