version: '3.8'

services:
  nginx:
    build: .
    container_name: low-code-nginx
    ports:
      - "9000:9000"
    volumes:
      - ./lowCode:/usr/share/nginx/html
      - ./nginx.conf:/etc/nginx/nginx.conf
    restart: always
